version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      actions-minor:
        update-types:
          - "minor"
          - "patch"
    open-pull-requests-limit: 10

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      npm-development:
        dependency-type: development
        update-types:
          - "major"
          - "minor"
          - "patch"
      npm-production:
        dependency-type: production
        update-types:
          - "minor"
          - "patch"
    open-pull-requests-limit: 10
