export { default as Details } from './Details'
export { default as Experience } from './Experience'
export { default as Strengths } from './Strengths'
export { default as Profile } from './Profile'
export { default as Employment } from './Employment'
export { default as Education } from './Education'
export { default as Header } from './Header'
